# Generated by Django 6.0.6 on 2026-06-15 06:33

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['group__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='categorygroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='statementupload',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-txn_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='transactionstaging',
            options={'ordering': ['txn_date', 'id']},
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='txn_type',
            field=models.CharField(blank=True, choices=[('', 'Any'), ('credit', 'Credit'), ('debit', 'Debit')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='statementupload',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='statementupload',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='statementupload',
            name='statement_password_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='transactionstaging',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactionstaging',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='categoryrule',
            name='applies_to',
            field=models.CharField(choices=[('description', 'Description'), ('payee', 'Payee'), ('notes', 'Notes')], default='description', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('user', 'fingerprint'), name='unique_transaction_fingerprint_per_user'),
        ),
        migrations.AddConstraint(
            model_name='transactionstaging',
            constraint=models.UniqueConstraint(fields=('upload', 'fingerprint'), name='unique_staging_fingerprint_per_upload'),
        ),
    ]
