# Generated by Django 6.0.6 on 2026-06-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_category_options_alter_categorygroup_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_transaction_fingerprint_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='transactionstaging',
            name='unique_staging_fingerprint_per_upload',
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='statementupload',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='raw_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_type',
            field=models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('manual', 'Manual')], default='bank', max_length=20),
        ),
        migrations.AddField(
            model_name='transactionstaging',
            name='raw_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transactionstaging',
            name='source_type',
            field=models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('manual', 'Manual')], default='bank', max_length=20),
        ),
        migrations.AlterField(
            model_name='categoryrule',
            name='applies_to',
            field=models.CharField(choices=[('raw_description', 'Raw description'), ('description', 'Clean description'), ('payee', 'Payee'), ('notes', 'Notes')], default='payee', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionstaging',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
